### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by AtaIanta** [AIDungeonWiXAnon/AID2-Installer-Project#1]
Very good job anon, it surely will help many people install Clover. But can we change logo to the 4 leaf version, eventually 4chan logo which is in the game? I don't really like 3 leaf design, it's nice but lack of one leaf is sad.

**Comment by AIDungeonWiXAnon** [comment]
Thanks, glad it's being received well. As for the logo, it's actually on the TODO to be replaced already:
`
    <Icon Id="AppIcon" SourceFile="$(var.ProjectDir)SourceFiles\icon.ico" />
    <Property Id="ARPPRODUCTICON" Value="AppIcon" />`
Since the current version of Clover Edition doesn't have a usable .ico, I've just used placeholders for now for the ARP (the 4-leaf version) and for the installer logo (the 3-leaf one you're mentioning). Using 4chan's logo, in hindsight, seems like the better option. I'll see about getting that taken care of.

**Comment by AIDungeonWiXAnon** [comment]
Alright, this should be fixed as of 1ccc912
